### ISSUE TITLE
Text for Ember.String namespace deprecation is incomplete

### ISSUE THREAD

**Issue by chriskrycho** [ember-learn/deprecation-app#686] opened 2020-10-15 18:55 UTC
The [Ember.String namespace deprecation](https://deprecations.emberjs.com/v3.x#toc_ember-string-namespace) reads, in part:

> Starting with Ember v2.18.0 [TODO: update to proper version], the `@ember/string` package was extracted from the Ember codebase into a separate module.

Note the `[TODO: update to proper version]`! If someone can inform me of the actual version, I'm happy to submit a PR to fix it. 😅

**Comment by jaredgalanis** [comment] 2020-10-15 19:43
Oof, thanks for finding this @chriskrycho! 

To me, it looks like it was extracted here: https://github.com/emberjs/ember.js/pull/16530 and came in at `v3.3.0`.

**Comment by jaredgalanis** [comment] 2020-10-16 12:39
Possible duplicate of #322

**Comment by JamesS-M** [comment] 2020-10-16 13:03
I'm working on this!

**Closed** 2020-10-16 14:03 UTC
Labels: Hacktoberfest, good first issue

**Comment by jaredgalanis** [comment] 2020-10-16 14:07
@chriskrycho we discussed this with @locks and for now we're actually just going to remove the deprecations until [this work](emberjs/rfc-tracking#26) has progressed further.

**Comment by chriskrycho** [comment] 2020-10-16 17:33
That seems totally reasonable. Thanks for the quick follow-through!
